server:
  port: 8080
  servlet:
    context-path: /pa
    session:
      timeout: 24h

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///points_alliance?characterEncoding=utf8&serverTimezone=Hongkong&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true
#    url: jdbc:mysql://39.99.43.125:3306/points_alliance?characterEncoding=utf8&serverTimezone=Hongkong&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true
    #    url: jdbc:mysql://192.168.2.200:3306/points_alliance?characterEncoding=utf8&serverTimezone=Hongkong&useSSL=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: lin123456
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  config:logback.xml

mybatis-plus:
  type-aliases-package: com.jx.entity
  mapper-locations: classpath:mapper/*.xml

